on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: exponentialcherub/deploy-pi/.github/workflows/deploy-pi.yml@v1.0.2
    with:
      app-name: "queue"
      startup-cmd: "go run queue.go"
      branch: "main"
    secrets: inherit
